### ISSUE TITLE
When the matrix is split, it is no longer possible to sort by the whole matrix

### ISSUE THREAD

**Issue by katush** [Caleydo/lineup_app#15]
When the matrix is split, it is no longer possible to sort by the whole matrix - clicking the sort button on the main matrix header will result into sorting by it's first column:
![image](https://user-images.githubusercontent.com/8986080/43583118-cf56547e-965e-11e8-8c10-8fbc91a0272c.png)

**Comment by katush** [comment]
I suggest to remove the sorting feature for the whole matrix when its split - this way we would avoid cases when the user sets sorting of the whole matrix e.g., by average row value and then in the second sorting layer the sorting by a single matrix column, which doesn't make much sense anyway... if the user splits the matrix, he/she will probably want to work with individual columns

**Comment by thinkh** [comment]
This behavior is fixed with v4.0.0-alpha.8.

![taggle-split-matrix-sorting](https://user-images.githubusercontent.com/5851088/49225057-5db3f280-f3e3-11e8-9f05-9a3b47854705.gif)
