### ISSUE TITLE
Compress button on matrix doesn't work

### ISSUE THREAD

**Issue by katush** [Caleydo/lineup_app#16]
Once you split the matrix it is not possible to "de-split" it - I think the compress button should do that, but it doesn't work.

**Comment by katush** [comment]
@thinkh I tested it now and it does work somehow (not quite correctly though). If it is not easy to fix maybe you can temporarily remove the button?

**Comment by thinkh** [comment]
The compress action usually does something else: It should aggregate the all columns to a slim column (i.e., shrink the composite column in width). However, this does not seem to work correctly.

I was hiding the corresponding toolbar options now in CSS. The better way might be to disable this options in the toolbar configuration, but I was not able to figure out how to do this in our LineUp app.

https://github.com/datavisyn/lineupjs/blob/d06c42af30281f08aa461790655a7a87c03ef06e/src/config.ts#L10
