### ISSUE TITLE
Gray out numerical columns

### ISSUE THREAD

**Issue by thinkh** [Caleydo/lineup_app#35]
All numerical columns should have gray bars. Only categorical columns should be colored by default.

**Comment by alexsb** [comment]
I don't. Order is still preserved, and as long as we can clearly distinguish where one bar ends and the other one begins, that's not an argument IMO.

**Comment by mstreit** [comment]
At the moment we would not be able to clearly distinguish where one bar ends and the next one starts. Adding some space between the stacked bar pieces might look weird. 
Also, we would also change the default LineUp behavior - which actually worked pretty well. So overall, I am not sure if this change would be an improvement. If there is a conflict of colors between some categories, the user can resolve this via the UI.

**Comment by thinkh** [comment]
I agree with @mstreit that we loose a main LineUp functionality when we use grey numerical columns for stacked bars. Two alternatives:

1. Grey out numerical columns by default and only color them when they are used in a stacked column
2. Use different shades of grey for different numerical columns

![image](https://user-images.githubusercontent.com/5851088/48050787-464a6680-e1a3-11e8-9073-410aaae5f624.png)

**Comment by mstreit** [comment]
re 2.: Different shades of grey might imply order, which is not good.

**Comment by thinkh** [comment]
@mstreit True.

**Comment by mstreit** [comment]
Also, as we decided to move the column stacking details to the Taggle suppl material, the issue is not very relevant for the Taggle paper.

**Comment by alexsb** [comment]
(a) they are ordered. 
(b) I don't think it is a strong effect, especially if you make the third one dark again.

**Comment by thinkh** [comment]
@zichner Thanks for your input. 

According to the comments above we should stick to the colored numerical columns. Hence I will close this issue for now. Reopen it if necessary.
