### ISSUE TITLE
Grouping hierarchy label empty for selection grouping

### ISSUE THREAD

**Issue by katush** [Caleydo/lineup_app#40]
If grouping by selection is active, the corresponding grouping hierarchy panel is missing a label (it should say something like grouping by selection):
![image](https://user-images.githubusercontent.com/8986080/48715007-466f4b00-ec14-11e8-836b-1e9c06f1fa75.png)

**Comment by mstreit** [comment]
@katush, please also test this issue (and other new issues) with the https://lineup.js.org/app_develop/ version as well. If the bug is present there as well, please file the bug in https://github.com/Caleydo/lineup_app so that Sam sees it as well. Thanks.

**Comment by katush** [comment]
@mstreit this is [https://github.com/Caleydo/lineup_app]() - do you mean [https://github.com/datavisyn/lineup_app]() ?

**Comment by mstreit** [comment]
yes, sorry.

**Comment by thinkh** [comment]
General bug -> moved to https://github.com/datavisyn/lineupjs/issues/110
